#!/bin/bash
# Quick Start Guide for Trading Dashboards

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 TRADING DASHBOARD - QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🏠 LOCAL DASHBOARD (Full Features + API)"
echo "   streamlit run local_dashboard.py"
echo "   → http://localhost:8501"
echo ""
echo "   Shows:"
echo "   • Live account data from Alpaca API"
echo "   • Current positions with P&L"
echo "   • Scanner results"
echo "   • Trading automation logs"
echo "   • Profit taker logs"
echo "   • Recent orders"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 PUBLIC DASHBOARD (Read-only, No API keys)"
echo "   streamlit run public_dashboard.py"
echo "   → http://localhost:8502"
echo ""
echo "   Shows:"
echo "   • System status"
echo "   • Sanitized activity feed"
echo "   • Scanner results"
echo "   • Portfolio decisions"
echo ""
echo "   Safe for public deployment on Streamlit Cloud"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔄 DATA FLOW"
echo "   Local: Trading scripts → public_events.json"
echo "   Cloud: ./sync_to_cloud.sh --watch → GitHub → Streamlit Cloud"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ FULL WORKFLOW"
echo "   1. Start local dashboard: streamlit run local_dashboard.py"
echo "   2. Run scanner: python daily_scanner.py --mode scan"
echo "   3. Run trading bot: python trading_automation.py --mode live"
echo "   4. Run profit taker: python intraday_profit_taker.py --mode moderate"
echo "   5. Sync to cloud: ./sync_to_cloud.sh --watch"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
